# Generated by Django 4.2.30 on 2026-05-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
